version: '3.3'
services:
  pg:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "demo"
      POSTGRES_USER: "demo"
      POSTGRES_DB: "demo"
    network_mode: host
    restart: always
    ports:
      - 5432:5432

  php:
    build:
      context: ./
    environment:
      APP_ENV: "dev"
      APP_SECRET: "2ca64f8d83b9e89f5f19d672841d6bb8"
      DATABASE_URL: "pgsql://demo:demo@127.0.0.1:5432/demo"
    network_mode: host
    restart: always
    ports:
      - 9000:9000

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    restart: always
    network_mode: host
    ports:
    - 80:80

  redis:
    image: redis
    network_mode: host
    ports:
      - 6379:6379
