apiVersion: v1
kind: Secret
metadata:
  name: fpm-system-envs
type: Opaque
data:
  DATABASE_URL: {{ include "demo-symfony.databaseurl" . }}
  REDIS_URL: {{ include "demo-symfony.redisurl" . }}
  REDIS_PATH: {{ include "demo-symfony.redispath" . }}
